## MSDS 7331: Data Mining

## Mini Lab: Logistic Regression and SVMs

## 9 June 2019

## Authors: Meredith Ludlow, Anand Rajan, Kristen Rollins, and Tej Tenmattam

---

### Create Models

<div class="alert alert-block alert-info">
<b>Rubric 1:</b> Create a logistic regression model and a support vector machine model for the classification task involved with your dataset. Assess how well each model performs (use 80/20 training/testing split for your data). Adjust parameters of the models to make them more accurate. If your dataset size requires the use of stochastic gradient descent, then linear kernel only is fine to use. That is, the SGDClassifier is fine to use for optimizing logistic regression and linear support vector machines. For many problems, SGD will be required in order to train the SVM model in a reasonable timeframe.
</div>

#### Preparing Data

In [1]:
# importing necessary packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

# Set seaborn plot styles
sns.set_style('darkgrid')
sns.set_color_codes('muted')

#uncomment when ready to turn in report
#import warnings
#warnings.filterwarnings("ignore") # ignore warnings for clean report

# df.head() displays all the columns without truncating
pd.set_option('display.max_columns', None)

# read csv file as pandas dataframe
df_17_census = pd.read_csv('Data/acs2017_census_tract_data.csv')

In [2]:
# Clean dataset as in lab 1
df_17_census.set_index('TractId', inplace=True) # set tract id as index

# Drop tracts where population is 0
df_17_cln = df_17_census.drop(df_17_census[df_17_census.TotalPop == 0].index)

# Drop tracts where child poverty or unemployment is null
df_17_cln = df_17_cln[np.isfinite(df_17_cln['ChildPoverty'])]
df_17_cln = df_17_cln[np.isfinite(df_17_cln['Unemployment'])]

# Impute to the median by each state
df_grouped = df_17_cln.groupby('State').transform(lambda x: x.fillna(x.median()))
df_17_cln['Income'] = df_grouped['Income']
df_17_cln['IncomeErr'] = df_grouped['IncomeErr']

# Impute remaining values to the overall median
df_17_cln = df_17_cln.fillna(df_17_cln.median())

In [3]:
# Categorize the unemployed percentages into binary categories
# Make cutoff using median of clean dataset, so groups are roughly equal
df_17_cln['HighUnemployment'] = pd.cut(df_17_cln.Unemployment,[-1,6,101],labels=[0,1])                                 
df_17_cln.HighUnemployment = df_17_cln.HighUnemployment.astype(np.int)
# 0 indicates low unemployment rate, 1 indicates high unemployment rate

df_17_cln.info() # matches cleaned dataset from lab 1

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72889 entries, 1001020100 to 72153750602
Data columns (total 37 columns):
State               72889 non-null object
County              72889 non-null object
TotalPop            72889 non-null int64
Men                 72889 non-null int64
Women               72889 non-null int64
Hispanic            72889 non-null float64
White               72889 non-null float64
Black               72889 non-null float64
Native              72889 non-null float64
Asian               72889 non-null float64
Pacific             72889 non-null float64
VotingAgeCitizen    72889 non-null int64
Income              72889 non-null float64
IncomeErr           72889 non-null float64
IncomePerCap        72889 non-null float64
IncomePerCapErr     72889 non-null float64
Poverty             72889 non-null float64
ChildPoverty        72889 non-null float64
Professional        72889 non-null float64
Service             72889 non-null float64
Office              72889 

In [4]:
# Create dataframe to use in logistic and SVM models
df_17_model = df_17_cln.copy()

# Eliminate non-useful and redundant variables
del df_17_model['State'] # encoding would result in too many added variables
del df_17_model['County'] # encoding would result in too many added variables
del df_17_model['Men'] # redundant to keep men and women
del df_17_model['Unemployment'] # already encoded to binary

# Eliminate more variables based on correlation plot (TODO maybe remove more)
del df_17_model['IncomeErr'] # only need to keep one income-related variable
del df_17_model['IncomePerCap'] # only need to keep one income-related variable
del df_17_model['IncomePerCapErr'] # only need to keep one income-related variable
del df_17_model['Transit'] # drive and transit were essentially inverses
del df_17_model['PublicWork'] # private and public work were essentially inverses

# All remaining variables are ints or floats so we do not have to do one-hot encoding

# Convert columns to percentages for consistency
df_17_model['Women'] = round(df_17_model['Women']/df_17_model['TotalPop']*100,1)
df_17_model['VotingAgeCitizen'] = round(df_17_model['VotingAgeCitizen']/df_17_model['TotalPop']*100,1)
df_17_model['Employed'] = round(df_17_model['Employed']/df_17_model['TotalPop']*100,1)

# TODO maybe further dimension reduction via PCA

print(df_17_model.info())
df_17_model.head()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 72889 entries, 1001020100 to 72153750602
Data columns (total 28 columns):
TotalPop            72889 non-null int64
Women               72889 non-null float64
Hispanic            72889 non-null float64
White               72889 non-null float64
Black               72889 non-null float64
Native              72889 non-null float64
Asian               72889 non-null float64
Pacific             72889 non-null float64
VotingAgeCitizen    72889 non-null float64
Income              72889 non-null float64
Poverty             72889 non-null float64
ChildPoverty        72889 non-null float64
Professional        72889 non-null float64
Service             72889 non-null float64
Office              72889 non-null float64
Construction        72889 non-null float64
Production          72889 non-null float64
Drive               72889 non-null float64
Carpool             72889 non-null float64
Walk                72889 non-null float64
OtherTransp       

TotalPop  Women  Hispanic  White  Black  Native  Asian  Pacific  \
TractId                                                                       
1001020100      1845   51.3       2.4   86.3    5.2     0.0    1.2      0.0   
1001020200      2172   46.3       1.1   41.6   54.5     0.0    1.0      0.0   
1001020300      3385   54.7       8.0   61.4   26.5     0.6    0.7      0.4   
1001020400      4267   53.1       9.6   80.3    7.1     0.5    0.2      0.0   
1001020500      9965   49.3       0.9   77.5   16.4     0.0    3.1      0.0   

            VotingAgeCitizen   Income  Poverty  ChildPoverty  Professional  \
TractId                                                                      
1001020100              76.3  67826.0     10.7          20.8          38.5   
1001020200              76.1  41287.0     22.4          35.8          30.5   
1001020300              73.3  46806.0     14.7          21.1          27.9   
1001020400              76.3  55895.0      2.3           1.7          29.0   
1001020500              72.5  68143.0     12.2          17.9          48.8   

            Service  Office  Construction  Production  Drive  Carpool  Walk  \
TractId                                                                       
1001020100     15.6    22.8          10.8        12.4   94.2      3.3   0.5   
1001020200     24.9    22.9           6.3        15.4   90.5      9.1   0.0   
1001020300     19.4    33.3           9.9         9.6   88.3      8.4   1.0   
1001020400     16.6    25.8           9.1        19.5   82.3     11.2   1.5   
1001020500     13.8    20.5           3.5        13.4   86.9     11.2   0.8   

            OtherTransp  WorkAtHome  MeanCommute  Employed  PrivateWork  \
TractId                                                                   
1001020100          0.0         2.1         24.5      47.8         74.2   
1001020200          0.5         0.0         22.2      39.2         75.9   
1001020300          0.8         1.5         23.1      43.8         73.3   
1001020400          2.9         2.1         25.9      43.3         75.8   
1001020500          0.3         0.7         21.0      48.0         71.4   

            SelfEmployed  FamilyWork  HighUnemployment  
TractId                                                 
1001020100           4.5         0.0                 0  
1001020200           9.0         0.0                 0  
1001020300           4.8         0.7                 0  
1001020400           4.5         0.0                 1  
1001020500           4.5         0.0                 0

#### Train/Test Split

In [5]:
# Following code from Dr. Larson's Logits and SVM notebook
# Question: should we actually use cross-validation for this lab? (rubric doesn't mention it)
from sklearn.model_selection import ShuffleSplit

# we want to predict the X and y data as follows:
if 'HighUnemployment' in df_17_model:
    y = df_17_model['HighUnemployment'].values # get the labels we want
    del df_17_model['HighUnemployment'] # get rid of the class label
    X = df_17_model.values # use everything else to predict
    
# 10 fold cross-validation
num_cv_iterations = 10
num_instances = len(y)
cv_object = ShuffleSplit(n_splits=num_cv_iterations,
                         test_size  = 0.2)
                         
print(cv_object)

ShuffleSplit(n_splits=10, random_state=None, test_size=0.2, train_size=None)


#### Logistic Regression

In [6]:
# run logistic regression and vary some parameters
from sklearn.linear_model import LogisticRegression
from sklearn import metrics as mt
# also scale variables
from sklearn.preprocessing import StandardScaler
scl_obj = StandardScaler()

# TODO repeat and try out different learning parameters and constants
# TODO try to fix warnings
lr_clf = LogisticRegression(penalty='l2', C=0.05, class_weight=None) 
        #class_weight=None because unemployment groups are weighted equally

for iter_num, (train_indices, test_indices) in enumerate(cv_object.split(X,y)):
    # scale attributes by the training set
    scl_obj.fit(X[train_indices])
    X_train_scaled = scl_obj.transform(X[train_indices]) # apply to training
    X_test_scaled = scl_obj.transform(X[test_indices]) # use training scales to adjust test set, so we're not cheating
    
    # train object
    lr_clf.fit(X_train_scaled,y[train_indices])
    # get test set precitions
    y_hat = lr_clf.predict(X_test_scaled)

    # print the accuracy and confusion matrix 
    print("====Iteration",iter_num," ====")
    print("accuracy", mt.accuracy_score(y[test_indices],y_hat)) 
    print("confusion matrix\n",mt.confusion_matrix(y[test_indices],y_hat))

/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 0  ====
accuracy 0.745575524763342
confusion matrix
 [[5789 1536]
 [2173 5080]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 1  ====
accuracy 0.7436548223350253
confusion matrix
 [[5762 1563]
 [2174 5079]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 2  ====
accuracy 0.7446837700644807
confusion matrix
 [[5803 1555]
 [2167 5053]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 3  ====
accuracy 0.7468788585539855
confusion matrix
 [[5903 1546]
 [2144 4985]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 4  ====
accuracy 0.7418713129373028
confusion matrix
 [[5731 1637]
 [2126 5084]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 5  ====
accuracy 0.745575524763342
confusion matrix
 [[5825 1564]
 [2145 5044]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 6  ====
accuracy 0.7457813143092331
confusion matrix
 [[5814 1563]
 [2143 5058]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 7  ====
accuracy 0.7463300864316093
confusion matrix
 [[5839 1557]
 [2141 5041]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 8  ====
accuracy 0.739676224447798
confusion matrix
 [[5803 1638]
 [2157 4980]]


/Users/kristenmccrary/anaconda3/envs/data_mining/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


====Iteration 9  ====
accuracy 0.7469474550692825
confusion matrix
 [[5892 1535]
 [2154 4997]]


#### Support Vector Machine

### Model Advantages

<div class="alert alert-block alert-info">
<b>Rubric 2:</b> Discuss the advantages of each model for each classification task. Does one type of model offer superior performance over another in terms of prediction accuracy? In terms of training time or efficiency? Explain in detail.
</div>

### Interpret Feature Importance

<div class="alert alert-block alert-info">
<b>Rubric 3:</b> Use the weights from logistic regression to interpret the importance of different features for the classification task. Explain your interpretation in detail. Why do you think some variables are more important?
</div>

In [7]:
# TODO use best logistic model we find (lr_clf object)
# sort attributes by weight and spit them out
zip_vars = zip(lr_clf.coef_.T,df_17_model.columns) # combine attributes
zip_vars = sorted(zip_vars)
for coef, name in zip_vars:
    print(name, 'has weight of', coef[0]) # now print them out

White has weight of -1.0877580661437716
Employed has weight of -0.6433136267451702
Hispanic has weight of -0.46595382599076873
Black has weight of -0.305921103731918
Asian has weight of -0.21864260396207214
Income has weight of -0.15275117978917715
Professional has weight of -0.11232045473800638
ChildPoverty has weight of -0.08130040158344763
WorkAtHome has weight of -0.07040789803161154
Pacific has weight of -0.06412586057660227
Walk has weight of -0.05346050022263001
TotalPop has weight of -0.039475477851311884
Construction has weight of -0.03939367826950078
Native has weight of -0.03458302017462102
FamilyWork has weight of -0.030590715189962498
SelfEmployed has weight of -0.02219771023257836
Drive has weight of -0.00445408617184769
OtherTransp has weight of 0.03818328156548312
PrivateWork has weight of 0.044271905533371896
Office has weight of 0.04518728654711343
Production has weight of 0.057514215876318386
Carpool has weight of 0.05927099932857496
Women has weight of 0.07930374415

### Interpret Support Vectors

<div class="alert alert-block alert-info">
<b>Rubric 4:</b> Look at the chosen support vectors for the classification task. Do these provide any insight into the data? Explain. If you used stochastic gradient descent (and therefore did not explicitly solve for support vectors), try subsampling your data to train the SVC model— then analyze the support vectors from the subsampled dataset.
</div>